### ISSUE TITLE
Swiftlint to make style cohesive

### ISSUE THREAD

**Issue by ktvtrifork** [trifork/TriforkSwiftExtensions#46]
A simple potentially very permissive, set of swiftlint rules to for example disallow force trys and to make some of the styling more cohesive.

**Comment by ghost** [comment]
Not necessary in my opinion. I really don't like coding under linters. I trust that we can handle it without a linter.

💩✋🏻🙅🏻‍♂️😬 ⛔️🚫☠️
(just my opinion about linters)

**Comment by ghost** [comment]
Well. Right now the project i small. 
But if we get more contributors it might be a good idea to have a linter to catch most common mistakes.

**Comment by ktvtrifork** [comment]
So you do not believe, that a compile time linter, that catches things are a good thing? I'm mostly referring to the Linting part and not the style part, as the style part is far more dependent on a style specification that there is not; but the lint part (eg, this weak is useless, or other kinds of unused, or bad constructs ) could potentially help either review time, or things that will fall though.

https://github.com/realm/SwiftLint/blob/master/Rules.md
if you look though the "lint" part there is quite a lot of things, that may or may not be apparent for most people, or even experienced people.

**Comment by ghost** [comment]
I do see some qualities and I guess I am willing to give it a try as long as we leave the styling part out, but if it annoys me a tiny bit it will get disabled again! 🤪 (I have very bad experiences with linters - sorry)

**Comment by ghost** [comment]
> I do see some qualities and I guess I am willing to give it a try as long as we leave the styling part out, but if it annoys me a tiny bit it will get disabled again! 🤪 (I have very bad experiences with linters - sorry)

![grumpy-old-man-](https://user-images.githubusercontent.com/45285045/53023389-686baa00-345d-11e9-81b6-21bd4f38e920.jpg)
